plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\chris\\cackle-site\\out"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
base = "C:\\Users\\chris\\cackle-site\\website"

[build.environment]
NODE_VERSION = "20"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]